#Trying to run enaR analyses on suite of models
#Suite of models generated by Ecosense routines

#Author: Sarah J. Weisberg

# Tue Oct 12 15:41:48 2021 ------------------------------

#Install package
#Note that I had to pull from github; CRAN version is depreciated
#install.packages("xlsx")
library(devtools)
install_github('SEELab/enaR')
library(enaR)
install.packages("sna")
library(sna)

#First Ecosense, convert Rsim outputs to Rpath models
source(here('R/Rsim_Rpath_conversion.R'))

#Need to calculate respiration, exports, detritus input
#To do so, need to have pull unassim, M0, and F (fishing mortality)

#Count number of each group type
#ngroups <- nrow(REco.params)
nliving <- nrow(REco.params$model[Type <  2, ])
ndead   <- nrow(REco.params$model[Type == 2, ])

alt.networks<-as.list(rep(NA,length(alt.models)))
#alt.networks<-as.list(rep(NA,3))

for (i in 1:length(alt.models)) {
  #Copy params
  model<-alt.models[[i]]
  #Pull diet matrix
  diet<-model$DC
  #Get consumption values by DC*QB*
  QQ<-matrix(nrow = (nliving + ndead + 1),ncol=nliving)
  for (j in 1:nliving){
  QQ[,j]<-diet[,j]*model$QB[j]*model$Biomass[j]
  }
  #Ignore Imports
  QQ<-QQ[1:58,]
  colnames(QQ)<-groups[1:56]
  rownames(QQ)<-groups[1:58]
  #Sum discards
  Discards<-rowSums(model$Discards)
  Discards<-Discards[1:58]
  #Calculate flow to detritus
  #If EE >1, assume 0 M0
  M0<-ifelse(model$EE<1,model$PB*(1-model$EE),0)
  #M0<-model$PB*(1-model$EE)
  Detritus<-M0*model$Biomass+model$QB*model$Biomass*model$Unassim
  Detritus<-Detritus[1:58]
  #Deal with flow to detritus from discards
  #Should be equal to all flow to discards minus consumption by SeaBirds(45)
  DetInDisc<-sum(Discards)
  Detritus[58]<-DetInDisc-QQ[58,45]
  #Flow to detritus from detritus = 0
  Detritus[57]<-0
  #Bind diet matrix (QQ) with flow to detritus, discards
  QQ<-cbind(QQ,Detritus,Discards)
  #Calculate exports
  #First sum catch
  Catch<-rowSums(model$Landings)
  #Add positive biomass accumulation terms
  Export<-Catch+(ifelse(model$BA>0,model$BA,0))
  Export<-Export[1:58]
  #Calculate respiration
  #Assume detritus, discards have 0 respiration
  Resp<-((1-model$Unassim)*model$QB-model$PB)*model$Biomass
  Resp<-ifelse(Resp>0,Resp,0)
  Resp<-Resp[1:58]
  Resp[57:58]<-0
  #Deal with Primary Production
  #First, estimate GROSS production = Imports
  #P/B in Ecopath model gives NET production
  #Ratio of gross:net is going to be fixed based on EMAX
  gross_net<-4101.9/3281.5
  gross<-gross_net*model$PB[1]*model$Biomass[1]
  Resp[1]<-gross-(model$PB[1]*model$Biomass[1])
  #Calculate imports
  #Negative biomass accumulation terms
  #Gross primary production
  Import<-abs(ifelse(model$BA<0,model$BA,0))
  Import[1]<-gross
  Import<-Import[1:58]
  #Trim biomass
  Biomass<-model$Biomass[1:58]
  #Pack the model directly and store
  alt.networks[[i]]<-pack(flow = QQ,
             input = Import,
             export = Export,
             living = c(rep(TRUE,56),rep(FALSE,2)),
             respiration = Resp,
             storage = Biomass)
}

#Analyze suite of models
info<-lapply(alt.networks,enaAscendency)

enaAscendency(alt.networks[[1]])

AMI<-c()
for (i in 1:length(alt.models)){
  AMI[i]<-info[[i]][[2]]
}

#Make a boxplot of AMI and identify outliers
out <- boxplot.stats(AMI)$out
out_ind <- which(AMI %in% c(out))
out_ind

ASC<-c()
for (i in 1:length(alt.models)){
  ASC[i]<-info[[i]][[5]]
}

#Make a boxplot of Ascendancy and identify outliers
out <- boxplot.stats(ASC)$out
out_ind <- which(ASC %in% c(out))
out_ind

R<-c()
for (i in 1:length(alt.models)){
  R[i]<-info[[i]][[9]]
}

out <- boxplot.stats(R)$out
out_ind <- which(R %in% c(out))
out_ind


TL.lgcopes<-c()
for (i in 1:length(alt.models)){
  TL.lgcopes[i]<-alt.models[[i]]$TL[5]
}
TL.smcopes<-c()
for (i in 1:length(alt.models)){
  TL.smcopes[i]<-alt.models[[i]]$TL[6]
}
TL.cod<-c()
for (i in 1:length(alt.models)){
  TL.cod[i]<-alt.models[[i]]$TL[24]
}
TL.cusk<-c()
for (i in 1:length(alt.models)){
  TL.cusk[i]<-alt.models[[i]]$TL[30]
}

#Look at individual outlier models in an exploratory fashion
outlier.model<-alt.models[126]
webplot(outlier.model[[1]],labels=T,fleets=F,label.cex=0.7)

TLs<-matrix(ncol=length(alt.networks),nrow=length(groups))
for (i in 1:length(alt.models)){
  TLs[,i]<-alt.models[[i]]$TL
}
TLs<-as.data.frame(TLs)
rownames(TLs)<-groups

#Greatest R
outlier.model<-alt.models[129]
webplot(outlier.model[[1]],labels=T,fleets=F,label.cex=0.7)
